# kind create cluster --config ./01-one-master-two-slave.yaml --image kindest/node:v1.28.0 --wait 30m --name myk8s1
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
